name: Spike
description: Research / investigation
title: "[SPIKE] "
labels: ["spike"]
body:
  - type: textarea
    id: question
    attributes:
      label: Research Question
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Expected Outcome

  - type: textarea
    id: notes
    attributes:
      label: Notes
