name: User Story
description: Functional requirement
title: "[STORY] "
labels: ["story"]
body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      description: As a [user], I want [goal], so that [benefit]
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Use GIVEN / WHEN / THEN format
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Technical Notes

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
