name: Task
description: Implementation task
title: "[TASK] "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Implement

  - type: textarea
    id: done
    attributes:
      label: Definition of Done
